# docker-compose.yml

version: "3"

services:
  api:
    networks:
      - api_kaltengventura
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

networks:
  api_kaltengventura:
    external: true
