# docker-compose.yml

version: "3"

services:
  api:
    networks:
      - proxynet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

networks:
  proxynet:
    name: custom_network
